name: lk-sars2-env
channels:
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - python=3.6.12
  - xarray=0.16.1
  - numpy=1.19.1
  - pandas=1.1.3
  - scipy=1.5.2
  - matplotlib=3.3.1
  - seaborn
  - jupyter
  - pytest
  - pytest-datadir
  - netCDF4=1.5.3
  - click
  - statsmodels=0.12.0
  - biopython=1.78
  - scikit-learn=0.23.2
  - pot=0.7.0
